### ISSUE TITLE
Fix "Character Point" calculation

### ISSUE THREAD

**Issue by thanmazus** [thanmazus/game#5]
Re-use the passiveTotal and the math of GetTotalPoints to add a passive point to the total pool rather than read in from the HTML so these can be spent separately from passive weapon points. End goal is two types of pools : skill specific and character-wide

**Comment by Fargrim** [comment]
I believe I took care of this in this commit: https://github.com/thanmazus/game/commit/2f84aae0c5ae7ffb5f115b4ee8d5f657df1d4faa
